"""Placeable item definitions (structures, turrets, torches, etc.)."""

ITEMS = [
    {
        'id': 'torch',
        'name': 'Torch',
        'desc': 'Hold for light. [F] to place.',
        'category': 'placeable',
        'damage': 5, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'campfire',
        'name': 'Campfire Kit',
        'desc': 'Heals nearby. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'trap',
        'name': 'Spike Trap',
        'desc': 'Damages enemies. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'bed',
        'name': 'Bed',
        'desc': 'Sleep at night. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'wall',
        'name': 'Wood Wall',
        'desc': 'A defensive wall. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'stone_wall_b',
        'name': 'Stone Wall',
        'desc': 'Tough stone wall. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'turret',
        'name': 'Turret',
        'desc': 'Auto-attacks enemies. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': True, 'can_enhance': True, 'has_rarity': True,
    },
    {
        'id': 'chest',
        'name': 'Chest',
        'desc': 'Store items. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'door',
        'name': 'Door',
        'desc': 'Walk-through barrier. [F] place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'enchantment_table',
        'name': 'Enchantment Table',
        'desc': 'Enchant gear. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'greater_enchantment_table',
        'name': 'Greater Enchantment Table',
        'desc': 'Advanced enchanting. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'beacon',
        'name': 'Beacon',
        'desc': 'Large light. Attracts enemies at night. [F] to place.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
    {
        'id': 'stone_oven',
        'name': 'Stone Oven',
        'desc': 'Smelt ore into ingots. [F] to place, [E] to use.',
        'category': 'placeable',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': True,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': True,
    },
]
