"""Spell book item definitions (all tiers)."""

ITEMS = [
    # -- Fireball --
    {'id': 'spell_fireball',   'name': 'Fireball I Tome',     'desc': 'Cast fireball. [F] use.',          'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_fireball_2', 'name': 'Fireball II Tome',    'desc': 'Stronger fireball. [F] use.',      'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_fireball_3', 'name': 'Fireball III Tome',   'desc': 'Devastating fireball. [F] use.',   'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_fireball_4', 'name': 'Fireball IV Tome',    'desc': 'Ruinous fireball. [F] use.',       'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_fireball_5', 'name': 'Fireball V Tome',     'desc': 'Cataclysmic fireball. [F] use.',   'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Heal --
    {'id': 'spell_heal',       'name': 'Heal I Tome',         'desc': 'Heal yourself. [F] use.',          'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_heal_2',     'name': 'Heal II Tome',        'desc': 'Greater heal. [F] use.',           'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_heal_3',     'name': 'Heal III Tome',       'desc': 'Powerful heal. [F] use.',          'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_heal_4',     'name': 'Heal IV Tome',        'desc': 'Superior heal. [F] use.',          'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_heal_5',     'name': 'Heal V Tome',         'desc': 'Divine heal. [F] use.',            'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Lightning --
    {'id': 'spell_lightning',   'name': 'Lightning I Tome',    'desc': 'Cast lightning bolt. [F] use.',    'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_lightning_2', 'name': 'Lightning II Tome',   'desc': 'Stronger lightning. [F] use.',     'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_lightning_3', 'name': 'Lightning III Tome',  'desc': 'Devastating lightning. [F] use.',  'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_lightning_4', 'name': 'Lightning IV Tome',   'desc': 'Ruinous lightning. [F] use.',      'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_lightning_5', 'name': 'Lightning V Tome',    'desc': 'Cataclysmic lightning. [F] use.',  'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Ice Shard --
    {'id': 'spell_ice',         'name': 'Ice Shard I Tome',    'desc': 'Cast ice shard. Slows. [F] use.',  'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_ice_2',       'name': 'Ice Shard II Tome',   'desc': 'Stronger ice. Slows. [F] use.',    'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_ice_3',       'name': 'Ice Shard III Tome',  'desc': 'Devastating ice. Slows. [F] use.', 'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_ice_4',       'name': 'Ice Shard IV Tome',   'desc': 'Ruinous ice. Slows. [F] use.',     'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_ice_5',       'name': 'Ice Shard V Tome',    'desc': 'Cataclysmic ice. Slows. [F] use.', 'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Regen --
    {'id': 'spell_regen_1',     'name': 'Regen I Tome',        'desc': 'Applies Regen I. [F] use.',        'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_regen_2',     'name': 'Regen II Tome',       'desc': 'Applies Regen II. [F] use.',       'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_regen_3',     'name': 'Regen III Tome',      'desc': 'Applies Regen III. [F] use.',      'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_regen_4',     'name': 'Regen IV Tome',       'desc': 'Applies Regen IV. [F] use.',       'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_regen_5',     'name': 'Regen V Tome',        'desc': 'Applies Regen V. [F] use.',        'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Protection --
    {'id': 'spell_protection_1', 'name': 'Protection I Tome',  'desc': 'Applies Prot I. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_protection_2', 'name': 'Protection II Tome', 'desc': 'Applies Prot II. [F] use.',        'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_protection_3', 'name': 'Protection III Tome','desc': 'Applies Prot III. [F] use.',       'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_protection_4', 'name': 'Protection IV Tome', 'desc': 'Applies Prot IV. [F] use.',        'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_protection_5', 'name': 'Protection V Tome',  'desc': 'Applies Prot V. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Strength --
    {'id': 'spell_strength_1',   'name': 'Strength I Tome',    'desc': 'Applies Str I. [F] use.',          'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_strength_2',   'name': 'Strength II Tome',   'desc': 'Applies Str II. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_strength_3',   'name': 'Strength III Tome',  'desc': 'Applies Str III. [F] use.',        'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_strength_4',   'name': 'Strength IV Tome',   'desc': 'Applies Str IV. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_strength_5',   'name': 'Strength V Tome',    'desc': 'Applies Str V. [F] use.',          'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Levitate --
    {'id': 'spell_levitate_1',   'name': 'Levitate I Tome',    'desc': 'Levitate buff. [F] use.',           'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_levitate_2',   'name': 'Levitate II Tome',   'desc': 'Levitate buff. [F] use.',           'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_levitate_3',   'name': 'Levitate III Tome',  'desc': 'Levitate buff. [F] use.',           'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_levitate_4',   'name': 'Levitate IV Tome',   'desc': 'Levitate buff. [F] use.',           'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_levitate_5',   'name': 'Levitate V Tome',    'desc': 'Levitate buff. [F] use.',           'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    # -- Return --
    {'id': 'spell_return_1',     'name': 'Return I Tome',      'desc': 'Teleport to bed. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_return_2',     'name': 'Return II Tome',     'desc': 'Teleport to bed. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_return_3',     'name': 'Return III Tome',    'desc': 'Teleport to bed. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_return_4',     'name': 'Return IV Tome',     'desc': 'Teleport to bed. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
    {'id': 'spell_return_5',     'name': 'Return V Tome',      'desc': 'Teleport to bed. [F] use.',         'category': 'spell', 'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False, 'can_enchant': False, 'can_enhance': False, 'has_rarity': False},
]
