"""Material item definitions."""

ITEMS = [
    {
        'id': 'wood',
        'name': 'Wood',
        'desc': 'Basic building material.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'stone',
        'name': 'Stone',
        'desc': 'Hard and durable.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'stick',
        'name': 'Stick',
        'desc': 'A thin branch. Weak weapon.',
        'category': 'material',
        'damage': 3, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'iron',
        'name': 'Iron Ingot',
        'desc': 'Smelted metal for strong gear.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'cloth',
        'name': 'Cloth',
        'desc': 'Woven fabric for crafting.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'bone',
        'name': 'Bone',
        'desc': 'Dropped by skeletons.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'leather',
        'name': 'Leather',
        'desc': 'Animal hide, used for armor.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'diamond',
        'name': 'Diamond',
        'desc': 'Precious gemstone. Very rare.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'gunpowder',
        'name': 'Gunpowder',
        'desc': 'Explosive powder for crafting.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'iron_ore',
        'name': 'Iron Ore',
        'desc': 'Raw iron, found in caves.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'brilliant_diamond',
        'name': 'Brilliant Diamond',
        'desc': 'A dazzling gem forged from 9 diamonds.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'titanium_ore',
        'name': 'Titanium Ore',
        'desc': 'Rare ore found in caves.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
    {
        'id': 'titanium_ingot',
        'name': 'Titanium Ingot',
        'desc': 'Smelted titanium for superior gear.',
        'category': 'material',
        'damage': 0, 'harvest_bonus': 0, 'heal': 0, 'placeable': False,
        'can_enchant': False, 'can_enhance': False, 'has_rarity': False,
    },
]
