"""Game-wide constants for the sandbox RPG.

All values are sourced from game_controller.py (the single source of truth).
This module re-exports them so that existing ``from core.constants import X``
statements throughout the codebase continue to work unchanged.
"""
import os

# == Re-export ALL tuning variables from game_controller ==================
from game_controller import (                                         # noqa: F401
    # -- Screen / Display --
    SCREEN_WIDTH, SCREEN_HEIGHT, TILE_SIZE, FPS,
    MIN_WINDOW_WIDTH, MIN_WINDOW_HEIGHT,
    # -- World generation --
    WORLD_WIDTH, WORLD_HEIGHT,
    ELEVATION_SCALE, MOISTURE_SCALE, MOISTURE_OFFSET,
    ELEVATION_OCTAVES, MOISTURE_OCTAVES,
    # -- Colours --
    BLACK, WHITE, YELLOW, RED, GREEN, CYAN, GRAY, DARK_GRAY,
    ORANGE, PURPLE, DARK_BROWN, LIGHT_BLUE, DARK_GREEN,
    # -- Rarity tier colors --
    RARITY_COLOR_COMMON, RARITY_COLOR_RARE, RARITY_COLOR_EPIC,
    RARITY_COLOR_LEGENDARY, RARITY_COLOR_MYTHIC,
    RARITY_COLORS,
    # -- Enchantment element colors --
    ENCHANT_COLOR_FIRE, ENCHANT_COLOR_ICE, ENCHANT_COLOR_LIGHTNING,
    ENCHANT_COLOR_PROTECTION, ENCHANT_COLOR_REGEN, ENCHANT_COLOR_STRENGTH,
    # -- Spell tier colors --
    FIREBALL_1_COLOR, FIREBALL_2_COLOR, FIREBALL_3_COLOR,
    FIREBALL_4_COLOR, FIREBALL_5_COLOR,
    HEAL_1_COLOR, HEAL_2_COLOR, HEAL_3_COLOR, HEAL_4_COLOR, HEAL_5_COLOR,
    LIGHTNING_1_COLOR, LIGHTNING_2_COLOR, LIGHTNING_3_COLOR,
    LIGHTNING_4_COLOR, LIGHTNING_5_COLOR,
    ICE_1_COLOR, ICE_2_COLOR, ICE_3_COLOR, ICE_4_COLOR, ICE_5_COLOR,
    STRENGTH_1_COLOR, STRENGTH_2_COLOR, STRENGTH_3_COLOR,
    STRENGTH_4_COLOR, STRENGTH_5_COLOR,
    REGEN_1_COLOR, REGEN_2_COLOR, REGEN_3_COLOR,
    REGEN_4_COLOR, REGEN_5_COLOR,
    PROTECTION_1_COLOR, PROTECTION_2_COLOR, PROTECTION_3_COLOR,
    PROTECTION_4_COLOR, PROTECTION_5_COLOR,
    # -- Boss glow colors --
    BOSS_GLOW_GOLEM, BOSS_GLOW_LICH, BOSS_GLOW_DRAGON,
    BOSS_GLOW_NECROMANCER, BOSS_GLOW_TROLL_KING, BOSS_GLOW_DEFAULT,
    BOSS_GLOW_DRAGON_RED, BOSS_GLOW_DRAGON_GREEN,
    BOSS_GLOW_DRAGON_BLACK, BOSS_GLOW_DRAGON_WHITE,
    BOSS_GLOW_SHADOW_DRAGON,
    BOSS_GLOW_COLORS,
    # -- Elite enemy system --
    ELITE_GLOW_COLOR, ELITE_HP_MULT, ELITE_DMG_MULT, ELITE_XP_MULT,
    # -- New mob colors --
    MOB_COLOR_ORC_ARCHER, MOB_COLOR_HOBGOBLIN, MOB_COLOR_KOBOLD,
    MOB_COLOR_MEPHIT_FIRE, MOB_COLOR_MEPHIT_ICE, MOB_COLOR_MEPHIT_LIGHTNING,
    MOB_COLOR_OGRE, MOB_COLOR_OGRE_MAGE, MOB_COLOR_CENTAUR,
    MOB_COLOR_SNAKE, MOB_COLOR_BEAR, MOB_COLOR_GOLEM,
    MOB_COLOR_DRAGON_RED, MOB_COLOR_DRAGON_GREEN,
    MOB_COLOR_DRAGON_BLACK, MOB_COLOR_DRAGON_WHITE,
    MOB_COLOR_SHADOW_DRAGON,
    # -- Tile types --
    TILE_WATER, TILE_SAND, TILE_GRASS, TILE_DIRT,
    TILE_STONE_FLOOR, TILE_STONE_WALL, TILE_FOREST,
    TILE_CAVE_FLOOR, TILE_CAVE_ENTRANCE,
    # -- Cave system --
    CAVE_COUNT, CAVE_WIDTH, CAVE_HEIGHT,
    CAVE_WALL_DENSITY, CAVE_SMOOTH_PASSES,
    CAVE_MOB_TYPES, CAVE_MOB_COUNT,
    CAVE_BOSS_TYPES, CAVE_ORE_COUNT, CAVE_DIAMOND_COUNT,
    CAVE_HP_MULT, CAVE_DMG_MULT, CAVE_ENTRANCE_MIN_DIST,
    # -- Inventory --
    HOTBAR_CAPACITY, INVENTORY_SLOTS_PER_PAGE, INVENTORY_PAGES,
    INVENTORY_COLS, INVENTORY_TOTAL_SLOTS,
    # -- Player --
    PLAYER_FRICTION, PLAYER_COLLIDER_W, PLAYER_COLLIDER_H,
    STARTING_WOOD, STARTING_STONE, PLAYER_TORCH_LIGHT_RADIUS,
    # -- Placement preview --
    PLACEMENT_PREVIEW_COLOR, PLACEMENT_INVALID_COLOR,
    # -- Font sizes --
    FONT_SIZE_MAIN, FONT_SIZE_SM, FONT_SIZE_LG, FONT_SIZE_XL,
    # -- Melee / Ranged combat --
    SPEAR_ATTACK_RANGE, WEAPON_ATTACK_RANGE, UNARMED_ATTACK_RANGE,
    MELEE_KNOCKBACK_FORCE, ATTACK_ANIM_DURATION, INTERACT_COOLDOWN,
    # -- Contact / projectile damage --
    CONTACT_DAMAGE_RADIUS, PLAYER_HIT_INVULN,
    DAMAGE_FLASH_DURATION, HIT_SHAKE_AMOUNT, HIT_SHAKE_DURATION,
    ENEMY_PROJ_HIT_RADIUS, PROJ_SHAKE_AMOUNT, PROJ_SHAKE_DURATION,
    # -- Interaction ranges --
    INTERACT_RANGE, HARVEST_RANGE,
    # -- World population --
    TREE_COUNT, FOREST_TREE_COUNT, ROCK_COUNT,
    # -- Building / placeable HP --
    WALL_HP, STONE_WALL_HP_MULT, TURRET_HP,
    TURRET_RANGE, TURRET_DAMAGE, TURRET_COOLDOWN,
    CHEST_CAPACITY, CHEST_HP_VALUE,
    TRAP_HP, BED_HP, CAMPFIRE_HP,
    ENCHANT_TABLE_CAPACITY, ENCHANT_TABLE_HP,
    DOOR_HP, DOOR_COLLIDER_W, DOOR_COLLIDER_H,
    CAMPFIRE_BASE_HEAL, CAMPFIRE_HEAL_RADIUS, CAMPFIRE_HEAL_INTERVAL,
    CAMPFIRE_LIGHT_RADIUS, TORCH_LIGHT_RADIUS, REPAIR_RANGE,
    # -- HUD --
    NOTIFICATION_DURATION, HUD_REFRESH_INTERVAL, DMG_NUMBER_FLOAT_SPEED,
    MOB_HP_BAR_W, MOB_HP_BAR_H, PLACEABLE_HP_BAR_W, PLACEABLE_HP_BAR_H,
    HOTBAR_SLOTS, HOTBAR_SLOT_SIZE, HOTBAR_SLOT_GAP,
    # -- Save system --
    SAVE_SLOTS, QUICK_SAVE_SLOT,
    # -- UI theme extras --
    UI_BG_MAIN_MENU, UI_BG_PANEL, UI_BG_PANEL_DARK,
    UI_BG_BUTTON_NORMAL, UI_BG_BUTTON_HOVER, UI_BG_BUTTON_SELECTED,
    UI_BORDER_NORMAL, UI_BORDER_PANEL, UI_BORDER_LIGHT, UI_BORDER_DIALOG,
    UI_BORDER_BUTTON,
    UI_TEXT_NORMAL, UI_TEXT_MUTED, UI_TEXT_HIGHLIGHT, UI_NOTIFICATION_TEXT,
    # -- UI slot/grid --
    UI_SLOT_BG_NORMAL, UI_SLOT_BG_SELECTED, UI_SLOT_BG_HOVER,
    UI_SLOT_BORDER_NORMAL, UI_SLOT_SEPARATOR,
    UI_NAV_HOVER, UI_NAV_NORMAL,
    UI_SAVE_SLOT_SELECTED, UI_SPLIT_BUTTON_NORMAL,
    # -- UI action buttons --
    UI_CONFIRM_BUTTON, UI_CANCEL_BUTTON,
    UI_STAT_BUTTON_HOVER, UI_STAT_BUTTON_NORMAL,
    UI_UNEQUIP_HOVER, UI_UNEQUIP_NORMAL,
    UI_EQUIP_HOVER, UI_EQUIP_NORMAL,
    UI_DROPDOWN_HOVER, UI_DROPDOWN_NORMAL,
    # -- Crafting --
    UI_CRAFT_CAN_NORMAL, UI_CRAFT_CAN_HOVER, UI_CRAFT_CAN_BORDER,
    UI_CRAFT_CANNOT_NORMAL, UI_CRAFT_CANNOT_HOVER, UI_CRAFT_CANNOT_BORDER,
    # -- Progress bar defaults --
    UI_PROGRESS_FG, UI_PROGRESS_BG,
    # -- Drop confirm dialog --
    UI_DROP_DIALOG_BG, UI_DROP_DIALOG_BORDER,
    UI_DROP_YES_BUTTON, UI_DROP_NO_BUTTON,
    # -- Chest UI --
    UI_CHEST_PANEL_BG, UI_CHEST_SLOT_BG_NORMAL, UI_CHEST_SLOT_BG_HOVER,
    UI_CHEST_SORT_HOVER, UI_CHEST_SORT_NORMAL, UI_CHEST_SORT_BORDER,
    UI_CHEST_MOVE_HOVER, UI_CHEST_MOVE_NORMAL, UI_CHEST_MOVE_BORDER,
    # -- Enchantment table UI --
    UI_ENCHANT_PANEL_BG, UI_ENCHANT_PANEL_BORDER,
    UI_ENCHANT_SLOT_BG_NORMAL, UI_ENCHANT_SLOT_BG_HOVER,
    UI_ENCHANT_SLOT_BORDER,
    UI_ENCHANT_COMBINE_ACTIVE, UI_ENCHANT_COMBINE_ACTIVE_HOVER,
    UI_ENCHANT_COMBINE_ACTIVE_BORDER,
    UI_ENCHANT_COMBINE_INACTIVE, UI_ENCHANT_COMBINE_INACTIVE_BORDER,
    UI_ENCHANT_DIVIDER, UI_ENCHANT_FALLBACK,
    # -- Death screen --
    DEATH_BUTTON_HOVER, DEATH_BUTTON_NORMAL,
    # -- HUD status --
    HUD_STATUS_TEXT, HUD_RESOURCE_TEXT,
    # -- Spell targeting --
    SPELL_HELP_TEXT,
    # -- Placement borders --
    PLACEMENT_UPGRADE_BORDER,
    # -- Mob / boss / light / particle colors --
    MOB_HP_BAR_BG, MOB_HP_BAR_FILL,
    PLACEABLE_HP_BAR_BG, PLACEABLE_HP_BAR_FILL,
    LIGHT_COLOR_CAMPFIRE, LIGHT_COLOR_TORCH, LIGHT_COLOR_FIRE_ENCHANT,
    PARTICLE_COLOR_FIRE, PARTICLE_COLOR_ICE, PARTICLE_COLOR_LIGHTNING_ARC,
    PARTICLE_COLOR_TREE,
    PERIOD_COLOR_DAY, PERIOD_COLOR_DAWN, PERIOD_COLOR_DUSK, PERIOD_COLOR_NIGHT,
    HOTBAR_BG, HOTBAR_BORDER,
    HOTBAR_SLOT_SELECTED_BG, HOTBAR_SLOT_NORMAL_BG,
    HOTBAR_SELECTED_BORDER, HOTBAR_NORMAL_BORDER, HOTBAR_SLOT_NUMBER_COLOR,
    DARKNESS_OVERLAY_TINT, SLEEP_OVERLAY_BG,
    DEATH_SCREEN_OVERLAY, SPELL_COOLDOWN_OVERLAY, SPELL_TARGET_RETICLE,
    OPTIONS_BG, OPTIONS_BORDER,
    OPTIONS_BACK_HOVER, OPTIONS_BACK_NORMAL, OPTIONS_BACK_BORDER,
    OPTIONS_INFO_TEXT, VOLUME_SLIDER_BG, VOLUME_SLIDER_FILL,
    HUD_DUSK_WARNING, HUD_WORLD_EDGE_WARNING, HUD_CONTROL_HINT,
    HUD_BED_PROMPT_BG, HUD_BED_PROMPT_TEXT,
    HUD_REPAIR_DAMAGED_BG, HUD_REPAIR_DAMAGED_TEXT,
    HUD_REPAIR_NORMAL_BG, HUD_REPAIR_NORMAL_TEXT,
    HUD_HP_BAR_FG, HUD_HP_BAR_BG, HUD_XP_BAR_FG, HUD_XP_BAR_BG,
    ATTACK_ARC_COLOR, STONE_WALL_OVERLAY, STONE_WALL_BORDER,
    MINIMAP_COLOR_WATER, MINIMAP_COLOR_SAND, MINIMAP_COLOR_GRASS,
    MINIMAP_COLOR_DIRT, MINIMAP_COLOR_STONE_FLOOR, MINIMAP_COLOR_STONE_WALL,
    MINIMAP_COLOR_FOREST, MINIMAP_COLOR_CAVE_FLOOR,
    MINIMAP_COLOR_CAVE_ENTRANCE, MINIMAP_COLOR_PLAYER, MINIMAP_SIZE_PX,
    PLACEMENT_UPGRADE_PREVIEW_COLOR, PLACEMENT_VALID_BORDER, PLACEMENT_INVALID_BORDER,
    BOMB_COLOR,
)

# == Re-export data module constants for backward compatibility ============
from data.day_night import (                                          # noqa: F401
    DAY_LENGTH_BASE, NIGHT_SLEEP_SPEED_MULT,
    TIME_NIGHT_END, TIME_DAY_START, TIME_DAY_END, TIME_NIGHT_START,
    DAY_FLASH_DURATION, NIGHT_FLASH_DURATION,
    DAY_FLASH_FADE_DIVISOR, DAY_FLASH_TEXT, DAY_FLASH_COLOR,
    NIGHT_FLASH_FADE_DIVISOR, NIGHT_FLASH_TEXT, NIGHT_FLASH_COLOR,
    DAWN_FLASH_DURATION, DAWN_FLASH_TEXT, DAWN_FLASH_COLOR,
    DUSK_FLASH_DURATION, DUSK_FLASH_TEXT, DUSK_FLASH_COLOR,
    SLEEP_OVERLAY_TEXT, SLEEP_OVERLAY_COLOR,
    NIGHT_DARKNESS_THRESHOLD,
    NIGHT_DAMAGE_BASE, NIGHT_DAMAGE_INCREASE, NIGHT_DAMAGE_INCREASE_FREQ,
    NIGHT_DAMAGE_INTERVAL, LIGHT_SAFETY_RADIUS,
    TIME_SPEED_NORMAL, SLEEP_DURATION, SLEEP_SPEED_MULT, BED_INTERACT_RANGE,
)
from data.day_events import (                                         # noqa: F401
    WAVE_START_NIGHT, WAVE_BASE_COUNT, WAVE_SCALE_PER_NIGHT,
    WAVE_SPAWN_RADIUS, WAVE_SPAWN_RADIUS_VARIANCE,
    WAVE_DAY_BONUS_PER_DAY,
    WAVE_SPAWN_INITIAL_INTERVAL, WAVE_SPAWN_MIN_INTERVAL,
    WAVE_INTERVAL_REDUCTION, WAVE_SPAWN_BATCH, WAVE_RANGED_MOB_CHANCE,
    NIGHT_WAVE_COUNT, NIGHT_WAVE_SPACING_HOURS,
    MOB_RESPAWN_INTERVAL, MOB_RESPAWN_MIN_DIST, MOB_MAX_COUNT, MOB_RESPAWN_BATCH,
    RANGED_ENEMY_START_DAY,
    PER_DAY_SCALE_FACTOR, MOB_SPAWN_ATTEMPTS,
    GRASS_MOB_SPAWN_CHANCE, FOREST_MOB_SPAWN_CHANCE, DIRT_MOB_SPAWN_CHANCE,
    ORC_SPAWN_CHANCE, GHOST_SPAWN_CHANCE, DARK_KNIGHT_SPAWN_CHANCE,
    NIGHT_MOB_SPAWN_CHANCE,
    INITIAL_MOB_SPAWNS,
    RESOURCE_RESPAWN_DAYS, CAVE_RESET_DAYS,
)
from data.stats import (                                              # noqa: F401
    STAT_POINTS_PER_LEVEL,
    STR_DAMAGE_MULT, BASE_MELEE_DAMAGE, BASE_MELEE_DAMAGE_MIN,
    LEVEL_DAMAGE_MULT,
    AGI_SPEED_BONUS, AGI_SPEED_BONUS_CAP,
    PLAYER_BASE_SPEED, MOVEMENT_ACCEL_MULT,
    SPRITE_FLIP_THRESHOLD,
    AGILITY_COOLDOWN_REDUCTION, BASE_ATTACK_COOLDOWN, MIN_ATTACK_COOLDOWN,
    AGI_RANGED_SPEED_BONUS, AGI_RANGED_SPEED_BONUS_CAP,
    AGI_RANGED_DAMAGE_MULT, MIN_RANGED_COOLDOWN,
    LEVEL_UP_BASE_HP, VIT_HP_BONUS_PER_LEVEL, VITALITY_CAMPFIRE_BONUS_PER,
    CRIT_CHANCE_PER_LUCK, CRIT_DAMAGE_MULT, LUCK_HARVEST_CHANCE,
)
from data.difficulty import (                                          # noqa: F401
    DIFFICULTY_EASY, DIFFICULTY_NORMAL, DIFFICULTY_HARD, DIFFICULTY_HARDCORE,
    DIFFICULTY_NAMES, DIFFICULTY_MULTIPLIERS, DIFFICULTY_PROFILES,
    get_profile as get_difficulty_profile,
)

# -- Enhancement re-exports ------------------------------------------------
from core.enhancement import (                                        # noqa: F401
    TURRET_ENHANCE_DAMAGE, TURRET_ENHANCE_HP, TURRET_ENHANCE_DR,
)

# -- Save system (path derived from project root, not from game_controller) --
_PROJECT_ROOT: str = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAVE_DIR: str = os.path.join(_PROJECT_ROOT, "save")
