"""Game-wide constants for the sandbox RPG.

All values are sourced from game_controller.py (the single source of truth).
This module re-exports them so that existing ``from core.constants import X``
statements throughout the codebase continue to work unchanged.
"""
import os

# == Re-export ALL tuning variables from game_controller ==================
from game_controller import (                                         # noqa: F401
    # -- Screen / Display --
    SCREEN_WIDTH, SCREEN_HEIGHT, TILE_SIZE, FPS,
    MIN_WINDOW_WIDTH, MIN_WINDOW_HEIGHT,
    # -- World generation --
    WORLD_WIDTH, WORLD_HEIGHT,
    ELEVATION_SCALE, MOISTURE_SCALE, MOISTURE_OFFSET,
    ELEVATION_OCTAVES, MOISTURE_OCTAVES,
    # -- Colours --
    BLACK, WHITE, YELLOW, RED, GREEN, CYAN, GRAY, DARK_GRAY,
    ORANGE, PURPLE, DARK_BROWN, LIGHT_BLUE, DARK_GREEN,
    # -- Rarity tier colors --
    RARITY_COLOR_COMMON, RARITY_COLOR_RARE, RARITY_COLOR_EPIC,
    RARITY_COLOR_LEGENDARY, RARITY_COLOR_MYTHIC,
    RARITY_COLORS,
    # -- Enhancement level colors --
    ENHANCEMENT_COLOR_1, ENHANCEMENT_COLOR_2, ENHANCEMENT_COLOR_3,
    ENHANCEMENT_COLOR_4, ENHANCEMENT_COLOR_5,
    # -- Enchantment element colors --
    ENCHANT_COLOR_FIRE, ENCHANT_COLOR_ICE, ENCHANT_COLOR_LIGHTNING,
    ENCHANT_COLOR_PROTECTION, ENCHANT_COLOR_REGEN, ENCHANT_COLOR_STRENGTH,
    # -- Boss glow colors --
    BOSS_GLOW_GOLEM, BOSS_GLOW_LICH, BOSS_GLOW_DRAGON,
    BOSS_GLOW_NECROMANCER, BOSS_GLOW_TROLL_KING, BOSS_GLOW_DEFAULT,
    BOSS_GLOW_COLORS,
    # -- Tile types --
    TILE_WATER, TILE_SAND, TILE_GRASS, TILE_DIRT,
    TILE_STONE_FLOOR, TILE_STONE_WALL, TILE_FOREST,
    TILE_CAVE_FLOOR, TILE_CAVE_ENTRANCE,
    # -- Cave system --
    CAVE_COUNT, CAVE_WIDTH, CAVE_HEIGHT,
    CAVE_WALL_DENSITY, CAVE_SMOOTH_PASSES,
    CAVE_MOB_TYPES, CAVE_MOB_COUNT,
    CAVE_BOSS_TYPES, CAVE_ORE_COUNT, CAVE_DIAMOND_COUNT,
    CAVE_HP_MULT, CAVE_DMG_MULT, CAVE_ENTRANCE_MIN_DIST,
    # -- Inventory --
    HOTBAR_CAPACITY, INVENTORY_SLOTS_PER_PAGE, INVENTORY_PAGES,
    INVENTORY_COLS, INVENTORY_TOTAL_SLOTS,
    # -- Player --
    PLAYER_FRICTION, PLAYER_COLLIDER_W, PLAYER_COLLIDER_H,
    STARTING_WOOD, STARTING_STONE, PLAYER_TORCH_LIGHT_RADIUS,
    # -- Placement preview --
    PLACEMENT_PREVIEW_COLOR, PLACEMENT_INVALID_COLOR,
    # -- Font sizes --
    FONT_SIZE_MAIN, FONT_SIZE_SM, FONT_SIZE_LG, FONT_SIZE_XL,
    # -- Melee / Ranged combat --
    SPEAR_ATTACK_RANGE, WEAPON_ATTACK_RANGE, UNARMED_ATTACK_RANGE,
    MELEE_KNOCKBACK_FORCE, ATTACK_ANIM_DURATION, INTERACT_COOLDOWN,
    # -- Contact / projectile damage --
    CONTACT_DAMAGE_RADIUS, PLAYER_HIT_INVULN,
    DAMAGE_FLASH_DURATION, HIT_SHAKE_AMOUNT, HIT_SHAKE_DURATION,
    ENEMY_PROJ_HIT_RADIUS, PROJ_SHAKE_AMOUNT, PROJ_SHAKE_DURATION,
    # -- Interaction ranges --
    INTERACT_RANGE, HARVEST_RANGE,
    # -- World population --
    TREE_COUNT, FOREST_TREE_COUNT, ROCK_COUNT,
    # -- Building / placeable HP --
    WALL_HP, STONE_WALL_HP_MULT, TURRET_HP,
    TURRET_RANGE, TURRET_DAMAGE, TURRET_COOLDOWN,
    CHEST_CAPACITY, CHEST_HP_VALUE,
    TRAP_HP, BED_HP, CAMPFIRE_HP,
    ENCHANT_TABLE_CAPACITY, ENCHANT_TABLE_HP,
    DOOR_HP, DOOR_COLLIDER_W, DOOR_COLLIDER_H,
    CAMPFIRE_BASE_HEAL, CAMPFIRE_HEAL_RADIUS, CAMPFIRE_HEAL_INTERVAL,
    CAMPFIRE_LIGHT_RADIUS, TORCH_LIGHT_RADIUS, REPAIR_RANGE,
    # -- HUD --
    NOTIFICATION_DURATION, HUD_REFRESH_INTERVAL, DMG_NUMBER_FLOAT_SPEED,
    MOB_HP_BAR_W, MOB_HP_BAR_H, PLACEABLE_HP_BAR_W, PLACEABLE_HP_BAR_H,
    HOTBAR_SLOTS, HOTBAR_SLOT_SIZE, HOTBAR_SLOT_GAP,
    # -- Save system --
    SAVE_SLOTS, QUICK_SAVE_SLOT,
)

# == Re-export data module constants for backward compatibility ============
from data.day_night import (                                          # noqa: F401
    DAY_LENGTH_BASE, NIGHT_SLEEP_SPEED_MULT,
    TIME_NIGHT_END, TIME_DAY_START, TIME_DAY_END, TIME_NIGHT_START,
    DAY_FLASH_DURATION, NIGHT_FLASH_DURATION,
    DAY_FLASH_FADE_DIVISOR, DAY_FLASH_TEXT, DAY_FLASH_COLOR,
    NIGHT_FLASH_FADE_DIVISOR, NIGHT_FLASH_TEXT, NIGHT_FLASH_COLOR,
    DAWN_FLASH_DURATION, DAWN_FLASH_TEXT, DAWN_FLASH_COLOR,
    DUSK_FLASH_DURATION, DUSK_FLASH_TEXT, DUSK_FLASH_COLOR,
    SLEEP_OVERLAY_TEXT, SLEEP_OVERLAY_COLOR,
    NIGHT_DARKNESS_THRESHOLD,
    NIGHT_DAMAGE_BASE, NIGHT_DAMAGE_INCREASE, NIGHT_DAMAGE_INCREASE_FREQ,
    NIGHT_DAMAGE_INTERVAL, LIGHT_SAFETY_RADIUS,
    TIME_SPEED_NORMAL, SLEEP_DURATION, SLEEP_SPEED_MULT, BED_INTERACT_RANGE,
)
from data.day_events import (                                         # noqa: F401
    WAVE_START_NIGHT, WAVE_BASE_COUNT, WAVE_SCALE_PER_NIGHT,
    WAVE_SPAWN_RADIUS, WAVE_SPAWN_RADIUS_VARIANCE,
    WAVE_DAY_BONUS_PER_DAY,
    WAVE_SPAWN_INITIAL_INTERVAL, WAVE_SPAWN_MIN_INTERVAL,
    WAVE_INTERVAL_REDUCTION, WAVE_SPAWN_BATCH, WAVE_RANGED_MOB_CHANCE,
    MOB_RESPAWN_INTERVAL, MOB_RESPAWN_MIN_DIST, MOB_MAX_COUNT, MOB_RESPAWN_BATCH,
    RANGED_ENEMY_START_DAY,
    PER_DAY_SCALE_FACTOR, MOB_SPAWN_ATTEMPTS,
    GRASS_MOB_SPAWN_CHANCE, FOREST_MOB_SPAWN_CHANCE, DIRT_MOB_SPAWN_CHANCE,
    ORC_SPAWN_CHANCE, GHOST_SPAWN_CHANCE, DARK_KNIGHT_SPAWN_CHANCE,
    NIGHT_MOB_SPAWN_CHANCE,
    INITIAL_MOB_SPAWNS,
    RESOURCE_RESPAWN_DAYS, CAVE_RESET_DAYS,
)
from data.stats import (                                              # noqa: F401
    STAT_POINTS_PER_LEVEL,
    STR_DAMAGE_MULT, BASE_MELEE_DAMAGE, BASE_MELEE_DAMAGE_MIN,
    LEVEL_DAMAGE_MULT,
    AGI_SPEED_BONUS, AGI_SPEED_BONUS_CAP,
    PLAYER_BASE_SPEED, MOVEMENT_ACCEL_MULT,
    SPRITE_FLIP_THRESHOLD,
    AGILITY_COOLDOWN_REDUCTION, BASE_ATTACK_COOLDOWN, MIN_ATTACK_COOLDOWN,
    AGI_RANGED_SPEED_BONUS, AGI_RANGED_SPEED_BONUS_CAP,
    AGI_RANGED_DAMAGE_MULT, MIN_RANGED_COOLDOWN,
    LEVEL_UP_BASE_HP, VIT_HP_BONUS_PER_LEVEL, VITALITY_CAMPFIRE_BONUS_PER,
    CRIT_CHANCE_PER_LUCK, CRIT_DAMAGE_MULT, LUCK_HARVEST_CHANCE,
)
from data.difficulty import (                                          # noqa: F401
    DIFFICULTY_EASY, DIFFICULTY_NORMAL, DIFFICULTY_HARD, DIFFICULTY_HARDCORE,
    DIFFICULTY_NAMES, DIFFICULTY_MULTIPLIERS, DIFFICULTY_PROFILES,
    get_profile as get_difficulty_profile,
)

# -- Enhancement re-exports ------------------------------------------------
from core.enhancement import (                                        # noqa: F401
    TURRET_ENHANCE_DAMAGE, TURRET_ENHANCE_HP, TURRET_ENHANCE_DR,
)

# -- Save system (path derived from project root, not from game_controller) --
_PROJECT_ROOT: str = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SAVE_DIR: str = os.path.join(_PROJECT_ROOT, "save")
