"""Loot tables for boss enemies and the cave loot chest.

Boss loot tables have the same base keys as normal tables plus:
    guaranteed      – list of (item_id, min_count, max_count) always dropped
    enhanced_chance – probability (0.0–1.0) that ONE pool drop is upgraded
                      to an enhanced (+1..+5) variant (using ENHANCEMENT_ODDS)

Cave chest loot is separate; it defines the contents placed into the
loot chest that spawns after a cave boss is killed.

Pool tuple format: (item_id, weight, min_count, max_count)
    item_id   – item identifier string
    weight    – relative selection weight (higher = more likely to be picked)
    min_count – minimum amount dropped if selected
    max_count – maximum amount dropped if selected
"""
from typing import Any, Dict

BOSS_LOOT: Dict[str, Dict[str, Any]] = {
    # ── Stone Golem Boss ──────────────────────────────────────────────
    'boss_golem': {
        'drop_chance': 1.0,          # 100% — always drops loot
        'min_items': 3,              # at least 3 distinct pool items
        'max_items': 5,              # at most 5 distinct pool items
        'guaranteed': [              # (item_id, min_count, max_count) — always given
            ('iron', 4, 8),
            ('stone', 5, 10),
        ],
        'enhanced_chance': 0.40,     # 40% chance one pool drop becomes +1..+5
        # Pool: (item_id, weight, min_count, max_count)
        'pool': [
            ('spell_fireball',     12, 1, 1),
            ('spell_fireball_2',    6, 1, 1),
            ('spell_fireball_3',    2, 1, 1),
            ('spell_lightning',    10, 1, 1),
            ('spell_lightning_2',   5, 1, 1),
            ('spell_lightning_3',   2, 1, 1),
            ('spell_ice',          10, 1, 1),
            ('spell_ice_2',         5, 1, 1),
            ('spell_ice_3',         2, 1, 1),
            ('spell_heal',          8, 1, 1),
            ('spell_heal_2',        4, 1, 1),
            ('spell_heal_3',        2, 1, 1),
            ('iron_sword',          8, 1, 1),
            ('iron_axe',            6, 1, 1),
            ('mace',                6, 1, 1),
            ('iron_armor',          6, 1, 1),
            ('iron_shield',         5, 1, 1),
            ('diamond',             8, 1, 3),
            ('health_potion',      10, 2, 4),
            ('spell_strength_1',     4, 1, 1),
            ('spell_strength_2',     3, 1, 1),
            ('spell_strength_3',     1, 1, 1),
            ('spell_protection_1',   4, 1, 1),
            ('spell_protection_2',   3, 1, 1),
            ('spell_protection_3',   1, 1, 1),
            ('spell_regen_1',        4, 1, 1),
            ('spell_regen_2',        3, 1, 1),
            ('spell_regen_3',        1, 1, 1),
            ('bomb',                5, 1, 3),
            ('gunpowder',           5, 2, 5),
            ('enchant_tome_1',      6, 1, 1),
            ('enchant_tome_2',      5, 1, 1),
            ('enchant_tome_3',      4, 1, 1),
            ('enchant_tome_4',      3, 1, 1),
            ('enchant_tome_5',      2, 1, 1),
            ('enchant_transfer_tome',  2, 1, 1),
            ('enhance_transfer_tome',  2, 1, 1),
            ('superior_transfer_tome', 1, 1, 1),
            ('disenchant_tome',        2, 1, 1),
            ('unenhance_tome',         2, 1, 1),
        ],
    },
    # ── Lich Boss ─────────────────────────────────────────────────────
    'boss_lich': {
        'drop_chance': 1.0,          # 100% — always drops loot
        'min_items': 3,              # at least 3 distinct pool items
        'max_items': 5,              # at most 5 distinct pool items
        'guaranteed': [              # (item_id, min_count, max_count) — always given
            ('bone', 5, 8),
            ('cloth', 3, 5),
        ],
        'enhanced_chance': 0.50,     # 50% chance one pool drop becomes +1..+5
        # Pool: (item_id, weight, min_count, max_count)
        'pool': [
            ('spell_lightning',    14, 1, 1),
            ('spell_lightning_2',   7, 1, 1),
            ('spell_lightning_3',   4, 1, 1),
            ('spell_lightning_4',   2, 1, 1),
            ('spell_ice',          12, 1, 1),
            ('spell_ice_2',         6, 1, 1),
            ('spell_ice_3',         3, 1, 1),
            ('spell_ice_4',         2, 1, 1),
            ('spell_fireball',     10, 1, 1),
            ('spell_fireball_2',    5, 1, 1),
            ('spell_fireball_3',    3, 1, 1),
            ('spell_fireball_4',    2, 1, 1),
            ('spell_heal',         10, 1, 1),
            ('spell_heal_2',        5, 1, 1),
            ('spell_heal_3',        3, 1, 1),
            ('spell_heal_4',        1, 1, 1),
            ('iron_sword',          5, 1, 1),
            ('mace',                5, 1, 1),
            ('iron_armor',          5, 1, 1),
            ('iron_shield',         4, 1, 1),
            ('diamond',            10, 1, 3),
            ('health_potion',       8, 2, 4),
            ('spell_regen_2',        4, 1, 1),
            ('spell_regen_3',        2, 1, 1),
            ('spell_regen_4',        1, 1, 1),
            ('spell_strength_2',     4, 1, 1),
            ('spell_strength_3',     2, 1, 1),
            ('spell_strength_4',     1, 1, 1),
            ('spell_protection_2',   4, 1, 1),
            ('spell_protection_3',   2, 1, 1),
            ('spell_protection_4',   1, 1, 1),
            ('bomb',                4, 1, 2),
            ('gunpowder',           4, 2, 4),
            ('enchant_tome_3',      5, 1, 1),
            ('enchant_tome_4',      4, 1, 1),
            ('enchant_tome_5',      3, 1, 1),
            ('enchant_transfer_tome',  3, 1, 1),
            ('enhance_transfer_tome',  3, 1, 1),
            ('superior_transfer_tome', 1, 1, 1),
            ('disenchant_tome',        3, 1, 1),
            ('unenhance_tome',         3, 1, 1),
        ],
    },
    # ── Dragon Boss ───────────────────────────────────────────────────
    'boss_dragon': {
        'drop_chance': 1.0,
        'min_items': 4,
        'max_items': 6,
        'guaranteed': [
            ('iron', 6, 12),
            ('diamond', 2, 4),
        ],
        'enhanced_chance': 0.55,
        'pool': [
            ('spell_fireball_2',    8, 1, 1),
            ('spell_fireball_3',    5, 1, 1),
            ('spell_fireball_4',    3, 1, 1),
            ('spell_fireball_5',    1, 1, 1),
            ('spell_lightning_2',   6, 1, 1),
            ('spell_lightning_3',   4, 1, 1),
            ('spell_lightning_4',   2, 1, 1),
            ('spell_lightning_5',   1, 1, 1),
            ('spell_ice_2',         5, 1, 1),
            ('spell_ice_3',         3, 1, 1),
            ('spell_ice_4',         2, 1, 1),
            ('spell_ice_5',         1, 1, 1),
            ('spell_heal_2',        5, 1, 1),
            ('spell_heal_3',        3, 1, 1),
            ('spell_heal_4',        2, 1, 1),
            ('spell_heal_5',        1, 1, 1),
            ('iron_sword',          6, 1, 1),
            ('iron_axe',            6, 1, 1),
            ('mace',                5, 1, 1),
            ('iron_armor',          7, 1, 1),
            ('iron_shield',         5, 1, 1),
            ('diamond',            10, 1, 3),
            ('health_potion',      10, 2, 5),
            ('spell_strength_3',    4, 1, 1),
            ('spell_strength_4',    2, 1, 1),
            ('spell_strength_5',    1, 1, 1),
            ('spell_protection_3',  4, 1, 1),
            ('spell_protection_4',  2, 1, 1),
            ('spell_protection_5',  1, 1, 1),
            ('spell_regen_3',       4, 1, 1),
            ('spell_regen_4',       2, 1, 1),
            ('spell_regen_5',       1, 1, 1),
            ('bomb',                6, 2, 4),
            ('gunpowder',           6, 3, 6),
            ('enchant_tome_3',      5, 1, 1),
            ('enchant_tome_4',      4, 1, 1),
            ('enchant_tome_5',      3, 1, 1),
            ('enchant_transfer_tome',  3, 1, 1),
            ('enhance_transfer_tome',  3, 1, 1),
            ('superior_transfer_tome', 2, 1, 1),
            ('disenchant_tome',        3, 1, 1),
            ('unenhance_tome',         3, 1, 1),
        ],
    },
    # ── Necromancer Boss ──────────────────────────────────────────────
    'boss_necromancer': {
        'drop_chance': 1.0,
        'min_items': 3,
        'max_items': 5,
        'guaranteed': [
            ('bone', 6, 10),
            ('cloth', 4, 7),
        ],
        'enhanced_chance': 0.50,
        'pool': [
            ('spell_lightning',    12, 1, 1),
            ('spell_lightning_2',   6, 1, 1),
            ('spell_lightning_3',   3, 1, 1),
            ('spell_lightning_4',   1, 1, 1),
            ('spell_ice',          12, 1, 1),
            ('spell_ice_2',         6, 1, 1),
            ('spell_ice_3',         3, 1, 1),
            ('spell_ice_4',         1, 1, 1),
            ('spell_fireball',      8, 1, 1),
            ('spell_fireball_2',    4, 1, 1),
            ('spell_fireball_3',    2, 1, 1),
            ('spell_fireball_4',    1, 1, 1),
            ('spell_heal',         10, 1, 1),
            ('spell_heal_2',        5, 1, 1),
            ('spell_heal_3',        3, 1, 1),
            ('spell_heal_4',        1, 1, 1),
            ('iron_sword',          5, 1, 1),
            ('mace',                5, 1, 1),
            ('iron_armor',          5, 1, 1),
            ('iron_shield',         4, 1, 1),
            ('diamond',             8, 1, 2),
            ('health_potion',      10, 2, 4),
            ('spell_regen_2',       5, 1, 1),
            ('spell_regen_3',       3, 1, 1),
            ('spell_regen_4',       1, 1, 1),
            ('spell_strength_2',    4, 1, 1),
            ('spell_strength_3',    2, 1, 1),
            ('spell_strength_4',    1, 1, 1),
            ('spell_protection_2',  4, 1, 1),
            ('spell_protection_3',  2, 1, 1),
            ('spell_protection_4',  1, 1, 1),
            ('bomb',                4, 1, 3),
            ('gunpowder',           4, 2, 4),
            ('enchant_tome_2',      5, 1, 1),
            ('enchant_tome_3',      4, 1, 1),
            ('enchant_tome_4',      3, 1, 1),
            ('enchant_tome_5',      2, 1, 1),
            ('enchant_transfer_tome',  3, 1, 1),
            ('enhance_transfer_tome',  3, 1, 1),
            ('superior_transfer_tome', 1, 1, 1),
            ('disenchant_tome',        3, 1, 1),
            ('unenhance_tome',         3, 1, 1),
        ],
    },
    # ── Troll King Boss ───────────────────────────────────────────────
    'boss_troll_king': {
        'drop_chance': 1.0,
        'min_items': 4,
        'max_items': 6,
        'guaranteed': [
            ('iron', 8, 15),
            ('stone', 6, 12),
        ],
        'enhanced_chance': 0.45,
        'pool': [
            ('spell_fireball',     10, 1, 1),
            ('spell_fireball_2',    5, 1, 1),
            ('spell_fireball_3',    3, 1, 1),
            ('spell_fireball_4',    1, 1, 1),
            ('spell_lightning',    10, 1, 1),
            ('spell_lightning_2',   5, 1, 1),
            ('spell_lightning_3',   3, 1, 1),
            ('spell_lightning_4',   1, 1, 1),
            ('spell_ice',          10, 1, 1),
            ('spell_ice_2',         5, 1, 1),
            ('spell_ice_3',         3, 1, 1),
            ('spell_ice_4',         1, 1, 1),
            ('spell_heal',         10, 1, 1),
            ('spell_heal_2',        5, 1, 1),
            ('spell_heal_3',        3, 1, 1),
            ('spell_heal_4',        1, 1, 1),
            ('iron_sword',          8, 1, 1),
            ('iron_axe',            8, 1, 1),
            ('mace',                8, 1, 1),
            ('iron_armor',          8, 1, 1),
            ('iron_shield',         6, 1, 1),
            ('diamond',             8, 1, 3),
            ('health_potion',      12, 3, 6),
            ('spell_strength_2',    4, 1, 1),
            ('spell_strength_3',    2, 1, 1),
            ('spell_strength_4',    1, 1, 1),
            ('spell_protection_2',  4, 1, 1),
            ('spell_protection_3',  2, 1, 1),
            ('spell_protection_4',  1, 1, 1),
            ('spell_regen_2',       4, 1, 1),
            ('spell_regen_3',       2, 1, 1),
            ('spell_regen_4',       1, 1, 1),
            ('bomb',                6, 2, 4),
            ('gunpowder',           6, 3, 6),
            ('enchant_tome_2',      5, 1, 1),
            ('enchant_tome_3',      4, 1, 1),
            ('enchant_tome_4',      3, 1, 1),
            ('enchant_tome_5',      2, 1, 1),
            ('enchant_transfer_tome',  3, 1, 1),
            ('enhance_transfer_tome',  3, 1, 1),
            ('superior_transfer_tome', 1, 1, 1),
            ('disenchant_tome',        3, 1, 1),
            ('unenhance_tome',         3, 1, 1),
        ],
    },
}

# ── Cave Chest Loot ───────────────────────────────────────────────────
# Spawned after a cave boss is killed.
# 'base': guaranteed items placed in chest.  Format: (item_id, min_count, max_count)
# 'pool': weighted random items — same format as boss pools (item_id, weight, min, max)
# 'min_pool_rolls' / 'max_pool_rolls': how many distinct items to pull from pool
# 'enhanced_chance': probability that ONE pool item gets upgraded to +1..+5
CAVE_CHEST_LOOT: Dict[str, Any] = {
    'base': [
        ('iron',          5, 15),
        ('iron_ore',      3,  8),
        ('diamond',       1,  3),
        ('health_potion', 2,  5),
        ('gunpowder',     2,  6),
    ],
    'enhanced_chance': 0.50,
    'min_pool_rolls': 3,
    'max_pool_rolls': 6,
    'pool': [
        # -- Equipment --
        ('iron_sword',          8, 1, 1),
        ('iron_axe',            8, 1, 1),
        ('mace',                7, 1, 1),
        ('spear',               5, 1, 1),
        ('bone_club',           4, 1, 1),
        ('iron_armor',          7, 1, 1),
        ('leather_armor',       5, 1, 1),
        ('iron_shield',         6, 1, 1),
        ('wood_shield',         4, 1, 1),
        ('bow',                 5, 1, 1),
        ('crossbow',            3, 1, 1),
        ('sling',               3, 1, 1),
        # -- Ammo --
        ('arrow',               6, 10, 30),
        ('fire_arrow',          4,  5, 15),
        ('bolt',                4,  8, 20),
        ('sling_bullet',        3,  8, 15),
        # -- Spells (offensive) --
        ('spell_fireball',     10, 1, 1),
        ('spell_fireball_2',    6, 1, 1),
        ('spell_fireball_3',    3, 1, 1),
        ('spell_lightning',     8, 1, 1),
        ('spell_lightning_2',   5, 1, 1),
        ('spell_lightning_3',   3, 1, 1),
        ('spell_ice',           8, 1, 1),
        ('spell_ice_2',         5, 1, 1),
        ('spell_ice_3',         3, 1, 1),
        ('spell_heal',          8, 1, 1),
        ('spell_heal_2',        5, 1, 1),
        ('spell_heal_3',        3, 1, 1),
        # -- Spells (buff) --
        ('spell_strength_1',    4, 1, 1),
        ('spell_strength_2',    3, 1, 1),
        ('spell_strength_3',    2, 1, 1),
        ('spell_protection_1',  4, 1, 1),
        ('spell_protection_2',  3, 1, 1),
        ('spell_protection_3',  2, 1, 1),
        ('spell_regen_1',       4, 1, 1),
        ('spell_regen_2',       3, 1, 1),
        ('spell_regen_3',       2, 1, 1),
        # -- Tomes --
        ('enchant_tome_1',      6, 1, 1),
        ('enchant_tome_2',      5, 1, 1),
        ('enchant_tome_3',      4, 1, 1),
        ('enchant_tome_4',      3, 1, 1),
        ('enchant_tome_5',      2, 1, 1),
        ('enchant_transfer_tome',   2, 1, 1),
        ('enhance_transfer_tome',   2, 1, 1),
        ('superior_transfer_tome',  1, 1, 1),
        ('disenchant_tome',         2, 1, 1),
        ('unenhance_tome',          2, 1, 1),
        # -- Consumables --
        ('health_potion',       6, 2, 5),
        ('pie',                 4, 2, 4),
        ('bomb',                5, 1, 3),
        # -- Materials --
        ('diamond',             6, 1, 3),
    ],
}
